### ISSUE TITLE
Problem with the tutorial

### ISSUE THREAD

**Issue by ccarouge** [CWSL/cwsl-mas#47]
I want to try out the CWSLab Workflow tool so I started with the tutorial.
I've arrived at Step 2 (adding MergeTimeseries module). The tutorial says the workflow can then be run. If I execute there is the following error in MergeTimeseries module (as this module is red and the 2 previous ones are green):
Uncaught exception: "**init**() takes exactly 2 arguments (1 given)"

Traceback (most recent call last):
  File "/opt/cloudapps/vistrails/2.1.2/vistrails/core/modules/vistrails_module.py", line 400, in update
    self.compute()
  File "/home/561/ccc561/.vistrails/userpackages/cwsl/vt_modules/vt_cdscan.py", line 92, in compute
    execution_options=self._execution_options)
  File "/home/561/ccc561/.vistrails/userpackages/cwsl/core/process_unit.py", line 94, in __init__
    self.file_creator = FileCreator(output_pattern, final_constraints)
  File "/home/561/ccc561/.vistrails/userpackages/cwsl/core/file_creator.py", line 85, in **init**
    raise EmptyConstraintError
TypeError: **init**() takes exactly 2 arguments (1 given)

I have no idea what is missing.

**Comment by DamienIrving** [comment]
Hi @ccarouge. Thanks for spotting this bug with the tutorial. We've done some development work on the workflow tool recently and `MergeTimeseries` has been replaced and thus no longer exists. 

I'll tag this issue as a bug and someone will fix the tutorial in the coming days. In the meantime, there are a number of example workflows that do work in the [cwsl-workflows](https://github.com/CWSL/cwsl-workflows) repository. For example, open `warm_water_volume.vt` or `aus_mean_tas.vt` in VisTrails and try and execute those workflows instead.

**Comment by ccarouge** [comment]
Actually I've just figured out what was going on. I had a typing error in the constraint string for the constraint builder so I guess the CMIP5 module output was empty. It would be good to have a way to check the output of CMIP5 module after the constraint is applied. At least know how many "files" were found or if the output is empty? It might be there but it's not in the tutorial.

**Comment by jimjam-slam** [comment]
I also had a problem with the tutorial, though I worked it out. The tutorial uses the `Timeslice` module to cut the data series down to 2060–2080, but Nino3.4 subsequently fails:

```
ERROR: Rolling climatology requires at least 4 decades to calculate climatology
```

But it's fine if you give it a longer series (2035–2080, for example). I also used Crop, since [Timeslice wasn't available](http://climate-cms.unsw.wikispaces.net/Notes+on+CWSLab+Workflow+tool).
